//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由弘扬代码生成器自动生成http://code.hongyangcloud.com
//	   生成时间 2019-07-22 14:22:20  
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel;

namespace HongYang.Enterprise.UnitTests
{
    /// <summary>
    ///  集成平台消息日志表实体类
    /// </summary>
    public partial class Ep_log_message
    {
        /// <summary>
        ///  唯一ID
        /// </summary>
        [DisplayName("唯一ID")]
        [Required]
        [Key]
        public string Logid { get; set; }

        /// <summary>
        ///  消息来源
        /// </summary>
        [DisplayName("消息来源")]
        [Required]
        public string Sendfrom { get; set; }

        /// <summary>
        ///  消息接收
        /// </summary>
        [DisplayName("消息接收")]
        [Required]
        public string Sendto { get; set; }

        /// <summary>
        ///  消息发送时间
        /// </summary>
        [DisplayName("消息发送时间")]
        [Required]
        public DateTime? Sendtime { get; set; }

        /// <summary>
        ///  消息内容体
        /// </summary>
        [DisplayName("消息内容体")]
        [Required]
        public string Content { get; set; }

        /// <summary>
        ///  业务系统返回体
        /// </summary>
        [DisplayName("业务系统返回体")]
        [Required]
        public string Resultcontent { get; set; }

        /// <summary>
        ///  消息ID
        /// </summary>
        [DisplayName("消息ID")]
        [Required]
        public string Msgid { get; set; }

        /// <summary>
        ///  返回成功还是失败
        /// </summary>
        [DisplayName("返回成功还是失败")]
        [Required]
        public string Result { get; set; }

        /// <summary>
        ///  业务系统响应时间
        /// </summary>
        [DisplayName("业务系统响应时间")]
        [Required]
        public DateTime? Resulttime { get; set; }

        /// <summary>
        ///  如果未失败重发，这个则未原始ID
        /// </summary>
        [DisplayName("如果未失败重发，这个则未原始ID")]
        [Required]
        public string Groupid { get; set; }
    }
}
